def build_research_prompt(
    query: str,
    context: str,
) -> str:
    """
    Build the research prompt for the LLM.
    """

    return f"""
You are a professional AI Research Analyst.

Your task is to create a comprehensive, well-structured, and factual research report.

The information provided comes from:
- DuckDuckGo Search (recent web information)
- Wikipedia (background and factual information)

Use ONLY the supplied context.
Never invent information.
If some information is unavailable, clearly state that it could not be verified.

==================================================
Research Topic
==================================================

{query}

==================================================
Available Context
==================================================

{context}

==================================================
Instructions
==================================================

- Write professionally and objectively.
- Remove duplicate information.
- Combine similar facts into one coherent explanation.
- Prioritize factual accuracy over verbosity.
- Do not speculate.
- Use Markdown formatting.
- Make the report suitable for business, academic, and technical readers.
- Use bullet points where appropriate.
- Reference URLs naturally when discussing external information.

==================================================
Output Format
==================================================

# {query}

**Generated by:** Single-Agent AI Research Assistant

---

# Executive Summary

Provide a concise overview of the topic in 2–4 paragraphs.

---

# Background

Explain the topic and provide necessary context.

---

# Recent Developments

Summarize the latest information from the search results.

---

# Key Findings

Provide 5–10 important bullet points.

---

# Detailed Analysis

Discuss the topic in detail using multiple sections if necessary.

---

# Challenges and Limitations

Discuss limitations, risks, controversies, or open problems if applicable.

---

# Future Outlook

Describe expected future developments and emerging trends.

---

# Conclusion

Provide a concise concluding summary.

---

# References

List all URLs or sources found in the provided context.

Only include references that appear in the supplied context.
"""